

services:
  api-gateway:
    build:
      context: .  # Контекст сборки указывает на корень проекта
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "8080:8080"  # Порт для доступа снаружи
    depends_on:
      - user-service
      - task-service

  user-service:
    build:
      context: .  # Контекст сборки указывает на корень проекта
      dockerfile: ./user-service/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_PASSWORD=1234
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  task-service:
    build:
      context: .  # Контекст сборки указывает на корень проекта
      dockerfile: ./task-service/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_PASSWORD=1234
    depends_on:
      - postgres
    ports:
      - "8082:8082"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: